/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package itus.course.qc2015.king.gui;

import itus.course.qc2015.king.dao.impl.AttendanceDAO;
import itus.course.qc2015.king.model.Attendance;
import itus.course.qc2015.king.model.Student;
import itus.course.qc2015.king.model.Subject;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class AttendancesResult extends javax.swing.JFrame {

    /**
     * Creates new form AttendancesResult
     * @param s
     * @param sub
     */
    public AttendancesResult(Student s, Subject sub) {
        initComponents();
        this.s = s;
        this.sub = sub;
        txt_s_id.setText(s.getNumberId());
        txt_s_name.setText(s.getFullName());
        txt_s_course.setText(Integer.toString(s.getCourse()));
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        txt_s_major.setText(s.getMajor());

        txt_sub_id1.setText(sub.getSubjID());
        txt_sub_startdate.setText(sdf.format(sub.getBeginDate()));
        txt_sub_finishdate.setText(sdf.format(sub.getFinishDate()));
        txt_sub_day.setText(sub.getDay());
        txt_sub_startperiod.setText(sub.getBeginPeriod());
        txt_sub_finishperiod.setText(sub.getFinishPeriod());
        txt_sub_room.setText(sub.getRoom());
        List<Attendance> atts = new AttendanceDAO().getByForStudent(this.s.getNumberId(), this.sub.getSubjID());
           DefaultTableModel dm = (DefaultTableModel)jTable1.getModel();
           int ii=1;
           for (Attendance att : atts)
           {
               String status = att.getPresence() == 1 ? "Presence" : "Absent";
               Object[] row = new Object[2];
               row[0] = att.getWeek();
               row[1] = status;
                dm.addRow(row);
                ii++;
           }
           while(ii<=15) {

               Object[] row2 = new Object[2];
               row2[0] = ii;
               row2[1] = "NAN";
                dm.addRow(row2);
                ii++;
           }
    }

    private Student s;
    private Subject sub;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_sub_id = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txt_sub_id1 = new javax.swing.JLabel();
        txt_sub_name = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_sub_startdate = new javax.swing.JLabel();
        txt_sub_finishdate = new javax.swing.JLabel();
        txt_sub_day = new javax.swing.JLabel();
        txt_sub_startperiod = new javax.swing.JLabel();
        txt_sub_finishperiod = new javax.swing.JLabel();
        txt_sub_room = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_s_id = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txt_s_name = new javax.swing.JLabel();
        txt_s_course = new javax.swing.JLabel();
        txt_s_major = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txt_sub_id.setBackground(new java.awt.Color(0, 153, 51));
        txt_sub_id.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 255), 1, true));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 255));
        jLabel2.setText("Subject Info");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Id");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Name");

        jSeparator2.setBackground(new java.awt.Color(255, 204, 0));

        txt_sub_id1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_sub_id1.setForeground(new java.awt.Color(255, 255, 255));
        txt_sub_id1.setText("CTT2350");

        txt_sub_name.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_sub_name.setForeground(new java.awt.Color(255, 255, 255));
        txt_sub_name.setText("Java Application Development");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Starting date");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Finishing date");

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Day in week");

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Starting Period");

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Finishing Period");

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Room");

        txt_sub_startdate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_sub_startdate.setForeground(new java.awt.Color(255, 255, 255));
        txt_sub_startdate.setText("2018-02-22");

        txt_sub_finishdate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_sub_finishdate.setForeground(new java.awt.Color(255, 255, 255));
        txt_sub_finishdate.setText("2018-02-22");

        txt_sub_day.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_sub_day.setForeground(new java.awt.Color(255, 255, 255));
        txt_sub_day.setText("Monday");

        txt_sub_startperiod.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_sub_startperiod.setForeground(new java.awt.Color(255, 255, 255));
        txt_sub_startperiod.setText("15:10");

        txt_sub_finishperiod.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_sub_finishperiod.setForeground(new java.awt.Color(255, 255, 255));
        txt_sub_finishperiod.setText("12:30");

        txt_sub_room.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_sub_room.setForeground(new java.awt.Color(255, 255, 255));
        txt_sub_room.setText("F304");

        javax.swing.GroupLayout txt_sub_idLayout = new javax.swing.GroupLayout(txt_sub_id);
        txt_sub_id.setLayout(txt_sub_idLayout);
        txt_sub_idLayout.setHorizontalGroup(
            txt_sub_idLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txt_sub_idLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(txt_sub_idLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(txt_sub_idLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(36, 36, 36)
                        .addComponent(txt_sub_id1))
                    .addGroup(txt_sub_idLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(txt_sub_name))
                    .addComponent(jLabel2)
                    .addGroup(txt_sub_idLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txt_sub_startdate))
                    .addGroup(txt_sub_idLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, txt_sub_idLayout.createSequentialGroup()
                            .addComponent(jLabel15)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_sub_room))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, txt_sub_idLayout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_sub_finishperiod))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, txt_sub_idLayout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_sub_startperiod))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, txt_sub_idLayout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_sub_day))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, txt_sub_idLayout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addGap(18, 18, 18)
                            .addComponent(txt_sub_finishdate))))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        txt_sub_idLayout.setVerticalGroup(
            txt_sub_idLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txt_sub_idLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(txt_sub_idLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_sub_id1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(txt_sub_idLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_sub_name))
                .addGap(18, 18, 18)
                .addGroup(txt_sub_idLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_sub_startdate))
                .addGap(18, 18, 18)
                .addGroup(txt_sub_idLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txt_sub_finishdate))
                .addGap(18, 18, 18)
                .addGroup(txt_sub_idLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txt_sub_day))
                .addGap(18, 18, 18)
                .addGroup(txt_sub_idLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txt_sub_startperiod))
                .addGap(18, 18, 18)
                .addGroup(txt_sub_idLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txt_sub_finishperiod))
                .addGap(18, 18, 18)
                .addGroup(txt_sub_idLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txt_sub_room))
                .addContainerGap(161, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 255), 1, true));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel1.setText("Student Info");

        txt_s_id.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_s_id.setForeground(new java.awt.Color(255, 255, 255));
        txt_s_id.setText("1412183");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Id");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Name");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Course");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Major");

        jSeparator1.setBackground(new java.awt.Color(0, 204, 51));

        txt_s_name.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_s_name.setForeground(new java.awt.Color(255, 255, 255));
        txt_s_name.setText("Pham Quoc Hoang");

        txt_s_course.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_s_course.setForeground(new java.awt.Color(255, 255, 255));
        txt_s_course.setText("2014");

        txt_s_major.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_s_major.setForeground(new java.awt.Color(255, 255, 255));
        txt_s_major.setText("System Information");

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Week", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(60);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(160);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_s_name))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_s_course))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_s_major))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txt_s_id)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_s_id))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_s_name))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_s_course))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_s_major))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_sub_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txt_sub_id, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel txt_s_course;
    private javax.swing.JLabel txt_s_id;
    private javax.swing.JLabel txt_s_major;
    private javax.swing.JLabel txt_s_name;
    private javax.swing.JLabel txt_sub_day;
    private javax.swing.JLabel txt_sub_finishdate;
    private javax.swing.JLabel txt_sub_finishperiod;
    private javax.swing.JPanel txt_sub_id;
    private javax.swing.JLabel txt_sub_id1;
    private javax.swing.JLabel txt_sub_name;
    private javax.swing.JLabel txt_sub_room;
    private javax.swing.JLabel txt_sub_startdate;
    private javax.swing.JLabel txt_sub_startperiod;
    // End of variables declaration//GEN-END:variables
}
